/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AgregarJInternalFrame.java
 *
 * Created on 13-abr-2012, 11:20:47
 */
package vistas;
import modelos.*;
import controladoras.*;
import javax.swing.*;
/**
 *
 * @author CARLOS
 */
public class AgregarJInternalFrame extends javax.swing.JInternalFrame {
       private AdmUsuarios ae = new AdmUsuarios();
    /** Creates new form AgregarJInternalFrame */
    public AgregarJInternalFrame() {
        initComponents();
        inicialiar();
    }
    private void inicialiar() {
        limpiar();
        cargarUsuarios();
        cargarRol();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboRol = new javax.swing.JComboBox();
        txtPassWord = new javax.swing.JTextField();
        txtFechaIngreso = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtConfirmarPassWord = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtCodigoUsuario = new javax.swing.JTextField();
        chkGenerar = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Agregar Usuarios");

        cboRol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRolActionPerformed(evt);
            }
        });

        txtPassWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassWordActionPerformed(evt);
            }
        });

        jButton1.setText("Validar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtConfirmarPassWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmarPassWordActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel12.setText("ADMINISTRACION DE USUARIOS");

        txtApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPaternoActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });

        jLabel11.setText("Confirmar Contraseña");

        jLabel10.setText("Contraseña");

        jLabel9.setText("Rol");

        jLabel8.setText("Cargo");

        jLabel7.setText("Fecha de Ingreso");

        jLabel4.setText("Apellido Materno");

        jLabel6.setText("Correo");

        jLabel5.setText("Usuario");

        jLabel3.setText("Apellido Paterno");

        jLabel2.setText("Nombre");

        jLabel1.setText("DNI-Identificacion");

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel13.setText("Codigo");

        txtCodigoUsuario.setEditable(false);
        txtCodigoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoUsuarioActionPerformed(evt);
            }
        });

        chkGenerar.setSelected(true);
        chkGenerar.setText("Generar Código");
        chkGenerar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkGenerarStateChanged(evt);
            }
        });
        chkGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel10))
                                            .addGap(24, 24, 24))
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel5))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)
                                        .addGap(95, 95, 95))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCargo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPassWord, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtConfirmarPassWord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtApellidoPaterno)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                            .addComponent(txtDni, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                            .addComponent(txtCodigoUsuario))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                        .addComponent(chkGenerar)
                                        .addGap(37, 37, 37))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFechaIngreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(326, 326, 326))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(289, 289, 289))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(379, 379, 379)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkGenerar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConfirmarPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton3)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cboRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRolActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cboRolActionPerformed

private void txtPassWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassWordActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtPassWordActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
    try {
              JOptionPane.showMessageDialog(this, "UserName disponible", "Ingresar Empleado", JOptionPane.INFORMATION_MESSAGE);
              
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e);
        }
}//GEN-LAST:event_jButton1ActionPerformed

private void txtConfirmarPassWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmarPassWordActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtConfirmarPassWordActionPerformed

private void txtApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtApellidoPaternoActionPerformed

private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtNombreActionPerformed

private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed

}//GEN-LAST:event_txtDniActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 try {
            if (cargarCuenta()) {
                JOptionPane.showMessageDialog(this, "Empleado ingresado satisfactoriamente", "Ingresar Empleado", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e);
        }
                  
  
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
   limpiar(); 
}//GEN-LAST:event_jButton5ActionPerformed

private void txtCodigoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoUsuarioActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtCodigoUsuarioActionPerformed

private void chkGenerarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkGenerarStateChanged
        if (chkGenerar.isSelected()) {
            txtCodigoUsuario.setEditable(false);
        } else {
            txtCodigoUsuario.setEditable(true);
        }
}//GEN-LAST:event_chkGenerarStateChanged

private void chkGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGenerarActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_chkGenerarActionPerformed
private void cargarRol() {
        String rol[][] = {{"1", "Administrador"}, {"2", "Empleado"}, {"3", "Responsable"}};
        int size = rol.length;
        this.cboRol.removeAllItems();
        for (int i = 0; i < size; i++) {
            Rol item = new Rol();
            item.setItemData(rol[i][0]);
            item.setItem(rol[i][1]);
            this.cboRol.addItem(item);
        }
    }

    /*
     * Carga al Array de empleados desde el fichero
     */
    private void cargarUsuarios() {
        ae.cargarUsuarios();
        
    
    }
    
    
    /*
     * valida que se ingrese cada uno de los datos, ademas valida que el codigo del empleado no exista ya en el fichero e igual para el
     *  No. Seguro Social
     */
   private boolean cargarCuenta() throws Exception {
        try {
            Usuario emp = new Usuario();
            
            if (txtDni.getText().length() > 0) {
                 emp.setDni(txtDni.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Debe Ingresar el Dni ", "Ingresar Empleado", JOptionPane.ERROR_MESSAGE);
                return false;
            }

            if (this.txtNombre.getText().length() > 0) {
                emp.setNombre(this.txtNombre.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Debe Ingresar el nombre ", "Ingresar Empleado", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (this.txtApellidoPaterno.getText().length() > 0) {
                emp.setApellidoPaterno(this.txtApellidoPaterno.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Debe Ingresar el apellido Paterno", "Ingresar Empleado", JOptionPane.ERROR_MESSAGE);
                return false;
            }
             if (this.txtApellidoMaterno.getText().length() > 0) {
                emp.setApellidoMaterno(this.txtApellidoMaterno.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Debe Ingresar el apellido Materno", "Ingresar Empleado", JOptionPane.ERROR_MESSAGE);
                return false;
            }
             if (this.txtUserName.getText().length() > 0) {
                emp.setUserName(this.txtUserName.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Debe Ingresar el Usuario", "Ingresar Empleado", JOptionPane.ERROR_MESSAGE);
                return false;
            }
             if (this.txtCorreo.getText().length() > 0) {
                emp.setCorreoE(this.txtCorreo.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Debe Ingresar el Correo", "Ingresar Empleado", JOptionPane.ERROR_MESSAGE);
                return false;
            }
              if (this.txtFechaIngreso.getText().length() > 0) {
                emp.setFechaIngreso(this.txtFechaIngreso.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Debe Ingresar la Fecha de Ingreso", "Ingresar Empleado", JOptionPane.ERROR_MESSAGE);
                return false;
            }
              if (this.txtCargo.getText().length() > 0) {
                emp.setCargo(this.txtCargo.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Debe Ingresar el Cargo", "Ingresar Empleado", JOptionPane.ERROR_MESSAGE);
                return false;
            }
              if (this.txtPassWord.getText().length() > 0) {
                emp.setPassWord(this.txtPassWord.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Debe Ingresar la Contraseña", "Ingresar Empleado", JOptionPane.ERROR_MESSAGE);
                return false;
            }
              if (this.txtConfirmarPassWord.getText().length() > 0) {
                emp.setConfpassWord(this.txtConfirmarPassWord.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Debe Ingresar confirmacion de contraseña", "Ingresar Empleado", JOptionPane.ERROR_MESSAGE);
                return false;
            }

            
           
             //Agrega El empleado al arreglo de empleados
            ae.agregarUsuario(emp);
            //Guarda el arreglo de empleados al fichero
            ae.cargarArchivo();
           
           
           
            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e);
        }
        return true;
    }
   
   
//Para editar los textos de administracion de usuarios

public void editable(boolean v){
txtDni.setEditable(v);
txtNombre.setEditable(v);
txtApellidoPaterno.setEditable(v);
txtApellidoMaterno.setEditable(v);
txtUserName.setEditable(v);
txtCorreo.setEditable(v);
txtFechaIngreso.setEditable(v);
txtCargo.setEditable(v);
txtPassWord.setEditable(v);
txtConfirmarPassWord.setEditable(v);
cboRol.setEnabled(v);}

// mostrar
/*public void mostrar(String dni){
ae.();
Usuario x = ae.get(ae.buscar(dni));
txtDni.setText(x.getDni());
txtNombre.setText(x.getNombre());
txtApellidoPaterno.setText(x.getApellidoPaterno());
txtApellidoMaterno.setText(x.getApellidoMaterno());
txtUserName.setText(x.getUserName());
}*/



    private void limpiar() {
        this.txtDni.setText("");
        this.txtNombre.setText("");
        this.txtApellidoPaterno.setText("");
        this.txtApellidoMaterno.setText("");
        this.txtUserName.setText("");
        this.txtCorreo.setText("");
        this.txtFechaIngreso.setText("");
        this.txtCargo.setText("");
        this.txtPassWord.setText("");
        this.txtConfirmarPassWord.setText("");
        cargarRol();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboRol;
    private javax.swing.JCheckBox chkGenerar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCodigoUsuario;
    private javax.swing.JTextField txtConfirmarPassWord;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFechaIngreso;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassWord;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
