/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultarUsuarioForm.java
 *
 * Created on 13-abr-2012, 8:27:54
 */
package vistas;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import modelos.*;
import controladoras.*;
/**
 *
 * @author CARLOS
 */
public class ConsultarUsuarioForm extends javax.swing.JInternalFrame {

    private AdmUsuarios listaUsuario = new AdmUsuarios();
    /** Creates new form ConsultarUsuarioForm */
    public ConsultarUsuarioForm() {
        initComponents();
        inicialiar();
    }
    private void inicialiar() {
        limpiar();
        cargarUsuarios();
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUsuarios = new javax.swing.JList();

        setClosable(true);
        setIconifiable(true);
        setTitle("Consultar Usuario");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Usuarios Ingresados");

        lstUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstUsuariosMouseClicked(evt);
            }
        });
        lstUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lstUsuariosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(lstUsuarios);

        scrollPane1.add(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void lstUsuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstUsuariosKeyPressed

}//GEN-LAST:event_lstUsuariosKeyPressed

private void lstUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstUsuariosMouseClicked
 
}//GEN-LAST:event_lstUsuariosMouseClicked
/*
     * Segun lo ingresado en el campo de busqueda se realiza la busqueda en el arreglo de empleados
     */
    

    /*
     * Segun la posición en el listado muestra la info del empleado
     */
   

    /*
     * carga el listado con los datos del arreglo de empleados
     */
    private void cargarUsuarios() {
        ArrayList lst = new ArrayList();
        listaUsuario.cargarUsuarios();
        lst = listaUsuario.getListaUsuarios();
        this.lstUsuarios.removeAll();
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 0; i < lst.size(); i++) {
            Usuario e = new Usuario();
            e = (Usuario) lst.get(i);
            Rol item = new Rol();
            item.setItem("(" + String.valueOf(e.getCodigoUsuario()) + ") " + e.getDni() + ", " + e.getNombre() + ", " + e.getApellidoPaterno() + "," + e.getApellidoPaterno() + ", " + e.getConfpassWord() + ", " + e.getCargo() + ", " + e.getRol());
            item.setItemData(String.valueOf(e.getCodigoUsuario()));
            modelo.addElement(item);
        }
        this.lstUsuarios.setModel(modelo);
    }

    private void limpiar() {
        
        
        this.lstUsuarios.removeAll();
        
        
    }

    /*
     * cada vez que se mueve por el listado se verifica que tipo de empleado es
     */
    

    /*
     * carga el combobox de tipos de empleados
     */
   

    /*
     * hace set de los datos del empleado en las cajas de texto del fomulario
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstUsuarios;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
