/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrincipalJFrame.java
 *
 * Created on 13-abr-2012, 10:24:09
 */
package vistas;

/**
 *
 * @author CARLOS
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /** Creates new form PrincipalJFrame */
    public PrincipalJFrame() {
        initComponents();
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemAgregar = new javax.swing.JMenuItem();
        menuItemConsular = new javax.swing.JMenuItem();
        menuItemEditar = new javax.swing.JMenuItem();
        menuItemeliminar = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Opciones");

        menuItemAgregar.setText("Agregar");
        menuItemAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAgregarActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemAgregar);

        menuItemConsular.setText("Buscar");
        menuItemConsular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsularActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemConsular);

        menuItemEditar.setText("Editar");
        menuItemEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditarActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemEditar);

        menuItemeliminar.setText("Eliminar");
        menuItemeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemeliminarActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemeliminar);

        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void menuItemAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAgregarActionPerformed
 ingresarUsuario();
}//GEN-LAST:event_menuItemAgregarActionPerformed

private void menuItemConsularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsularActionPerformed
ConsultarUsuario();
}//GEN-LAST:event_menuItemConsularActionPerformed

private void menuItemEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditarActionPerformed
EditarUsuario();
}//GEN-LAST:event_menuItemEditarActionPerformed

private void menuItemeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemeliminarActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_menuItemeliminarActionPerformed

private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_menuItemSalirActionPerformed

private void ingresarUsuario() {
        AgregarJInternalFrame agregar = new AgregarJInternalFrame();
        agregar.setBounds(210, 100, 22, 39);
        jDesktopPane1.add(agregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        agregar.pack();
        agregar.show();
    }
/*
    private void EliminarEmpleado() {
        JInternalFrameEliminarEmp eliminar = new JInternalFrameEliminarEmp();
        eliminar.setBounds(210, 100, 22, 39);
        jDesktopPane1.add(eliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        eliminar.pack();
        eliminar.show();
    }*/

    private void EditarUsuario() {
        EditarJInternalFrame editar = new EditarJInternalFrame();
        editar.setBounds(210, 100, 22, 39);
        jDesktopPane1.add(editar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        editar.pack();
        editar.show();
    }

    private void ConsultarUsuario() {
        ConsultarUsuarioForm consultar = new ConsultarUsuarioForm();
        consultar.setBounds(150, 100, 2, 12);
        jDesktopPane1.add(consultar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        consultar.pack();
        consultar.show();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItemAgregar;
    private javax.swing.JMenuItem menuItemConsular;
    private javax.swing.JMenuItem menuItemEditar;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenuItem menuItemeliminar;
    // End of variables declaration//GEN-END:variables
}
